env: "local"
storage_path: "postgres://user:password@localhost:5432/omnistage?sslmode=disable"
http_server:
  address: "localhost:8082"
  # Generate a random string: [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Max 256 }))
jwt_secret: "paste-a-long-random-string-here"